#!/usr/bin/env python3
"""Generate NT syscall number tables from config/syscall-tables/ TOML files.

Outputs:
  - guest/ntdll/src/syscall_nrs_{build}.h  — C header (#define NR_xxx 0x...)
  - crates/winemu-shared/src/nt_sysno/handler_id.rs  — NtHandlerId enum
  - crates/winemu-shared/src/nt_sysno/nr_{build}.rs  — Rust (pub const / table slice)
  - crates/winemu-shared/src/nt_sysno/mod.rs  — re-exports

Usage:
    python3 gen_nt_sysno.py \\
        --toml-dir       config/syscall-tables/ \\
        --handlers-toml  config/syscall-tables/win11-arm64.toml \\
        --out-c-dir      guest/ntdll/src \\
        --out-rs-dir     crates/winemu-shared/src/nt_sysno
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path


def nt_api_to_nr_macro(api_name: str) -> str:
    """Convert an NT API name to its NR_ macro name.

    Examples:
        NtWaitForSingleObject   -> NR_WAIT_FOR_SINGLE_OBJECT
        NtFsControlFile         -> NR_FS_CONTROL_FILE
        NtAllocateVirtualMemory -> NR_ALLOCATE_VIRTUAL_MEMORY
    """
    name = api_name[2:]  # strip 'Nt' prefix
    snake = re.sub(r'(?<=[a-z0-9])([A-Z])', r'_\1', name)
    return "NR_" + snake.upper()


def load_toml_table(path: Path) -> tuple[int, dict[str, int]]:
    """Parse a syscall-tables TOML file → (build_number, {ApiName: nr}).

    Only reads [meta] (for 'build') and [nt] sections.
    Values in [nt] must be integer literals: NtFoo = 0x1234 or NtFoo = 1234
    Insertion order of [nt] keys is preserved (Python 3.7+).
    """
    build = 0
    nt_table: dict[str, int] = {}
    section = ""
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("["):
            section = line[1:line.index("]")].strip()
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().split("#")[0].strip()  # strip inline comments
        if section == "meta" and key == "build":
            try:
                build = int(value)
            except ValueError:
                pass
        elif section == "nt":
            try:
                nt_table[key] = int(value, 0)
            except ValueError:
                pass
    return build, nt_table


def load_handler_list(path: Path) -> list[str]:
    """Read the [nt] section from a TOML and return NT API names in file order.

    The position of each name in the returned list is its handler_id ordinal.
    """
    _, nt_table = load_toml_table(path)
    return list(nt_table.keys())


def emit_c_header(path: Path, build: int, nt_table: dict[str, int]) -> None:
    """Emit guest/ntdll/src/syscall_nrs_{build}.h"""
    lines = [
        f"/* Auto-generated by gen_nt_sysno.py — do not edit manually. */",
        f"/* Windows ARM64 build {build} NT syscall numbers. */",
        f"#pragma once",
        "",
    ]
    for api_name, nr in nt_table.items():
        macro = nt_api_to_nr_macro(api_name)
        lines.append(f"#define {macro:<44} 0x{nr:04X}")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {path}  ({sum(1 for l in lines if l.startswith('#define'))} defines)")


def emit_rust_handler_enum(path: Path, handler_list: list[str]) -> None:
    """Emit crates/winemu-shared/src/nt_sysno/handler_id.rs — NtHandlerId enum.

    The enum is build-independent; ordinals match the index in NT_SYSNO_TABLE slices.
    """
    lines = [
        "// Auto-generated by gen_nt_sysno.py — do not edit manually.",
        "// NT kernel handler identifiers (build-independent).",
        "",
        "/// Identifies a kernel-handled NT syscall.",
        "/// The u8 ordinal is the handler_id stored in NT_SYSNO_TABLE slices.",
        "/// Ordinals are stable: append new variants at the end only.",
        "#[repr(u8)]",
        "#[derive(Clone, Copy, PartialEq, Eq)]",
        "#[allow(dead_code)]",
        "pub enum NtHandlerId {",
    ]
    for idx, api_name in enumerate(handler_list):
        variant = api_name[2:]  # strip 'Nt' prefix; name is already PascalCase
        lines.append(f"    {variant:<28} = {idx},")
    lines.append("}")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {path}  ({len(handler_list)} variants)")


def emit_rust_table(path: Path, build: int, nt_table: dict[str, int], handler_list: list[str]) -> None:
    """Emit crates/winemu-shared/src/nt_sysno/nr_{build}.rs — a static slice."""
    lines = [
        f"// Auto-generated by gen_nt_sysno.py — do not edit manually.",
        f"// Windows ARM64 build {build} NT syscall numbers.",
        "",
        f"/// (syscall_nr, handler_index) pairs for build {build}.",
        f"/// handler_index is the NtHandlerId ordinal from handler_id.rs.",
        f"pub static NT_SYSNO_TABLE_{build}: &[(u16, u8)] = &[",
    ]
    for idx, api_name in enumerate(handler_list):
        nr = nt_table.get(api_name)
        if nr is None:
            lines.append(f"    // {api_name} not found in build {build}")
            continue
        lines.append(f"    (0x{nr:04X}, {idx}),  // {api_name}")
    lines.append("];")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {path}  ({sum(1 for l in lines if l.startswith('    ('))} entries)")


def emit_rust_mod(path: Path, builds: list[int]) -> None:
    """Emit crates/winemu-shared/src/nt_sysno/mod.rs"""
    lines = [
        "// Auto-generated by gen_nt_sysno.py — do not edit manually.",
        "",
        "mod handler_id;",
        "pub use handler_id::NtHandlerId;",
        "",
    ]
    for b in builds:
        lines.append(f"mod nr_{b};")
    lines.append("")
    for b in builds:
        lines.append(f"pub use nr_{b}::NT_SYSNO_TABLE_{b};")
    lines.append("")
    lines += [
        "/// Look up the NT syscall table for the given Windows build number.",
        "/// Returns `None` if the build is not supported.",
        "pub fn nt_sysno_table_for_build(build: u32) -> Option<&'static [(u16, u8)]> {",
        "    match build {",
    ]
    for b in builds:
        lines.append(f"        {b} => Some(NT_SYSNO_TABLE_{b}),")
    lines += [
        "        _ => None,",
        "    }",
        "}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {path}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--toml-dir", required=True,
        help="Directory containing config/syscall-tables/*.toml files",
    )
    ap.add_argument(
        "--handlers-toml", required=True,
        help="TOML file whose [nt] key order defines handler_id ordinals (e.g. win11-arm64.toml)",
    )
    ap.add_argument(
        "--out-c-dir", required=True,
        help="Directory for C headers (guest/ntdll/src/)",
    )
    ap.add_argument(
        "--out-rs-dir", required=True,
        help="Directory for Rust files (crates/winemu-shared/src/nt_sysno/)",
    )
    args = ap.parse_args()

    toml_dir = Path(args.toml_dir)
    handlers_path = Path(args.handlers_toml)
    out_c_dir = Path(args.out_c_dir)
    out_rs_dir = Path(args.out_rs_dir)

    print(f"Loading handler list from {handlers_path.name} …")
    handler_list = load_handler_list(handlers_path)
    print(f"  {len(handler_list)} handlers")
    emit_rust_handler_enum(out_rs_dir / "handler_id.rs", handler_list)

    builds: list[int] = []
    for toml_path in sorted(toml_dir.glob("*.toml")):
        print(f"Processing {toml_path.name} …")
        build, nt_table = load_toml_table(toml_path)
        if build == 0:
            print(f"  WARNING: no build number found, skipping")
            continue
        if not nt_table:
            print(f"  WARNING: no [nt] entries found, skipping")
            continue
        builds.append(build)
        emit_c_header(out_c_dir / f"syscall_nrs_{build}.h", build, nt_table)
        emit_rust_table(out_rs_dir / f"nr_{build}.rs", build, nt_table, handler_list)

    emit_rust_mod(out_rs_dir / "mod.rs", builds)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
