#[allow(unused_imports)]
pub use winemu_shared::status::{
    BUFFER_TOO_SMALL, END_OF_FILE, INFO_LENGTH_MISMATCH, INVALID_HANDLE, INVALID_PARAMETER,
    NOT_COMMITTED, NOT_IMPLEMENTED, NO_MEMORY, NO_MORE_ENTRIES, NO_MORE_FILES,
    OBJECT_NAME_COLLISION, OBJECT_NAME_NOT_FOUND, SUCCESS,
};
