// nt/sysno_table.rs — Runtime NT syscall dispatch table.
//
// At boot the VMM passes the Windows build number via the SET_SYSCALL_TABLE
// hypercall.  We load the corresponding (nr, handler_id) pairs from the
// shared nt_sysno data and fill a flat 512-entry lookup array.
//
// handler_id 0xFF means "no kernel handler — forward to VMM".
// The array covers syscall numbers 0x0000..0x01FF (9-bit range).
// Numbers ≥ 0x0200 are always forwarded.

use core::cell::UnsafeCell;
use core::sync::atomic::{AtomicU8, Ordering};
use winemu_shared::nt_sysno::nt_sysno_table_for_build;

// NtHandlerId is auto-generated by gen_nt_sysno.py into
// crates/winemu-shared/src/nt_sysno/handler_id.rs.
pub use winemu_shared::nt_sysno::NtHandlerId;

// Maximum syscall number handled inline (exclusive upper bound).
pub const NR_TABLE_SIZE: usize = 0x200;
pub const HANDLER_NONE: u8 = 0xFF; // forward to VMM

// ── Global table ─────────────────────────────────────────────────────────────

struct SysnoTable {
    // handler_id for nr 0x000..0x1FF; 0xFF = forward to VMM
    table: UnsafeCell<[u8; NR_TABLE_SIZE]>,
    // build number currently loaded (0 = uninitialized)
    loaded_build: AtomicU8, // truncated; full build in loaded_build_full
    loaded_build_full: UnsafeCell<u32>,
}

unsafe impl Sync for SysnoTable {}

static SYSNO_TABLE: SysnoTable = SysnoTable {
    table: UnsafeCell::new([HANDLER_NONE; NR_TABLE_SIZE]),
    loaded_build: AtomicU8::new(0),
    loaded_build_full: UnsafeCell::new(0),
};

/// Load the syscall dispatch table for the given Windows build.
/// Safe to call once during early init (before any user threads run).
pub fn load_for_build(build: u32) {
    let current = unsafe { *SYSNO_TABLE.loaded_build_full.get() };
    if current == build {
        return; // already loaded
    }

    let entries = match nt_sysno_table_for_build(build) {
        Some(e) => e,
        None => {
            crate::kerror!("sysno_table: unsupported build {}, using defaults", build);
            return;
        }
    };

    let tbl = unsafe { &mut *SYSNO_TABLE.table.get() };
    // Reset to "forward all"
    tbl.fill(HANDLER_NONE);
    // Fill in known handlers
    for &(nr, handler_id) in entries {
        if (nr as usize) < NR_TABLE_SIZE {
            tbl[nr as usize] = handler_id;
        }
    }
    unsafe { *SYSNO_TABLE.loaded_build_full.get() = build };
    SYSNO_TABLE.loaded_build.store(1, Ordering::Release);
    crate::log::debug_print("sysno_table: loaded build ");
    crate::log::debug_u64(build as u64);
    crate::log::debug_print("\n");
}

/// Look up the handler id for a given NT syscall number.
/// Returns HANDLER_NONE (0xFF) if nr is out of range or unknown.
#[inline(always)]
pub fn lookup(nr: u16) -> u8 {
    let idx = nr as usize;
    if idx >= NR_TABLE_SIZE {
        return HANDLER_NONE;
    }
    // This is only read after load_for_build() completes and before any user
    // threads run — no concurrent writes at steady state.
    unsafe { (*SYSNO_TABLE.table.get())[idx] }
}
