/*
 * Minimal ntdll.dll stub for WinEmu (ARM64)
 * Compiled with aarch64-w64-mingw32-gcc from llvm-mingw
 */
#include <stdint.h>
#include <stddef.h>

/* NT syscall numbers — auto-generated per Windows build.
 * Injected via -include syscall_nrs_<BUILD>.h by the Makefile.
 * Generated by scripts/gen_nt_sysno.py from SyscallTables-master.
 * Default fallback to build 22631 if not injected. */
#ifndef NR_WRITE_FILE
#  include "syscall_nrs_22631.h"
#endif

#define NR_WINEMU_LOAD_DLL 0x0F00U

typedef uint32_t NTSTATUS;
typedef uint32_t ULONG;
typedef uint64_t ULONG_PTR;
typedef void*    HANDLE;
typedef uint16_t WCHAR;
typedef uint8_t  UCHAR;
typedef uint8_t  BYTE;
typedef uint16_t WORD;
typedef uint32_t DWORD;
typedef uint64_t DWORD64;
typedef int32_t  LONG;

#define STATUS_SUCCESS 0x00000000U
#define STATUS_NOT_IMPLEMENTED 0xC0000002U
#define STATUS_INVALID_PARAMETER 0xC000000DU
#define STATUS_NO_MEMORY 0xC0000017U
#define STATUS_NONCONTINUABLE_EXCEPTION 0xC0000025U
#define STATUS_INVALID_DISPOSITION 0xC0000026U
#define STATUS_UNWIND 0xC0000027U
#define STATUS_BAD_FUNCTION_TABLE 0xC00000FFU
#define STATUS_UNHANDLED_EXCEPTION 0xC000014BU
#define STATUS_UNWIND_CONSOLIDATE 0x80000029U

#ifdef _MSC_VER
#  define EXPORT __declspec(dllexport)
#else
#  define EXPORT __attribute__((visibility("default")))
#endif

/* ── Syscall helpers ─────────────────────────────────────────── */

static inline NTSTATUS syscall2(uint64_t nr, uint64_t a0, uint64_t a1) {
    register uint64_t x8 asm("x8") = nr;
    register uint64_t x0 asm("x0") = a0;
    register uint64_t x1 asm("x1") = a1;
    asm volatile("svc #0" : "+r"(x0) : "r"(x8), "r"(x1) : "memory", "x2","x3","x4","x5","x6","x7");
    return (NTSTATUS)x0;
}

static inline NTSTATUS syscall6(uint64_t nr,
    uint64_t a0, uint64_t a1, uint64_t a2,
    uint64_t a3, uint64_t a4, uint64_t a5)
{
    register uint64_t x8 asm("x8") = nr;
    register uint64_t x0 asm("x0") = a0;
    register uint64_t x1 asm("x1") = a1;
    register uint64_t x2 asm("x2") = a2;
    register uint64_t x3 asm("x3") = a3;
    register uint64_t x4 asm("x4") = a4;
    register uint64_t x5 asm("x5") = a5;
    asm volatile("svc #0" : "+r"(x0) : "r"(x8),"r"(x1),"r"(x2),"r"(x3),"r"(x4),"r"(x5) : "memory");
    return (NTSTATUS)x0;
}

static inline NTSTATUS syscall4(uint64_t nr,
    uint64_t a0, uint64_t a1, uint64_t a2, uint64_t a3)
{
    register uint64_t x8 asm("x8") = nr;
    register uint64_t x0 asm("x0") = a0;
    register uint64_t x1 asm("x1") = a1;
    register uint64_t x2 asm("x2") = a2;
    register uint64_t x3 asm("x3") = a3;
    asm volatile("svc #0" : "+r"(x0) : "r"(x8),"r"(x1),"r"(x2),"r"(x3) : "memory","x4","x5","x6","x7");
    return (NTSTATUS)x0;
}

EXPORT NTSTATUS NtQueryVirtualMemory(
    HANDLE process_handle, void* base_address, ULONG memory_information_class,
    void* memory_information, size_t memory_information_length, size_t* return_length);
